@extends('layouts.sahl')
@section('styles')

    <style>
        .bg-dark-myimg{
            background-image: url("{{ url('sahl/assets/image/about.jpg') }}") !important;
        }

        @media screen and (max-width: 767px) {
            .mb_about {
                margin-top: 10px !important;
            }
        }
        @media screen and (min-width: 768px) {
            .mb_about {
                margin-top: -110px !important;
            }
        }

        .h_style{
            color: #335062;
            border-bottom: 1px solid #335062;
            margin-bottom: 15px;
            font-weight: 400;
        }
    </style>

@endsection
@section('content')
    <div class="container-fluid bg-dark-myimg pb-md-5 mb-md-5 ">
        <div class="col-md-10 mx-auto">
            <div class="container py-md-5">
                <div class="rounded">
                    <div class="row py-4">
                        <div class="col-md-8 pt-md-3 mt-md-3">

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="background-color: white">
        <div class="container-fluid">
            <div class="col-10 offset-1">
                <div class="pd-content">
                    <h2 class="p-2" style="text-transform: capitalize; color: #335062">Terms and Conditions<br> Health Plan</h2>
                    <p>
                        By using this site, you signify your assent to these Terms and Conditions. If you do not agree to all of these Terms and Conditions, do not use this site! Sahl Health Inc. may revise and update these Terms and Conditions at any time. Your continued usage of the Sahl Health Website, Apps and Portal will mean you accept those changes.
                    </p>
                    <ul>
                        <li>"SahlHealth" or the "Apps" means “portal” <a href="https://www.sahlhealth.com">https://www.sahlhealth.com</a> and related web sites and any other Apps or systems we release.</li>
                        <li>"Company," "we," "us," or "our" means Sahl Health Inc., a corporation, and any other companies that are subsidiaries and affiliates of Sahl Health Inc. When used in the context of the company name, "SahlHealth" may also refer to Sahl Health Inc.
                        </li>
                        <li>"Content" means text, graphics, images and any other material entered, processed, contained on or accessed through the Apps, including Content created, modified, validated or submitted by Medical Experts.</li>
                        <li>"Services" means services provided through the system, portal, website and apps.</li>
                        <li>"Medical Expert" means an individual accepted to participate in the Sahl Health Medical Expert Community and who participates on the Apps or interacts with others on or through the Apps, or other specialists or professionals who participate on Sahl Health in their capacity as experts.</li>
                    </ul>

                    <h3 class="h_style">Introduction</h3>
                    <h4 class="h_style pt-3">Sahl Health Services</h4>
                    <p>Sahl Health Services connect you to affordable medical services and products in Africa, International health providers, trusted health information, answers, and tips all designed to help you feel good, smarter and live a healthier, happier, wealthier and longer life.</p>
                    <h4 class="h_style pt-3">Sahl Health is not for medical care</h4>
                    <p>On Sahl health no formal medical diagnosis, treatment, or prescriptions are allowed. all information provided on Sahl Health or in connection with any communications supported by Sahlhealth, including but not limited to communications with Sahlhealth medical experts is intended to be for general informational purposes only, and is in no way intended to create a medical expert - patient relationship as defined by state and federal law; Sahl health is not a substitute for professional medical diagnosis or treatment; and reliance on any information provided by Sahl health or any Sahl health medical experts is solely at your own risk.</p>
                    <h4 class="h_style pt-3">We Do Support Your Health Decisions (Sahl Health)</h4>
                    <p>Sahl Health is designed to support the health decisions and choices that you make. These decisions and choices are yours, and we believe that you are the best decision maker about your health and that these decisions should be made in connection with the advice you receive within a formal medical expert-patient relationship. Always use common sense when making health decisions. Sahl Health cannot make decisions for you. We can help you find good health information and, where available and appropriate, connect with health expert for care or for in-person care.</p>
                    <h4 class="h_style pt-3">We Don't Practice Medicine (Sahl Health)</h4>
                    <p>On Sahl Health you can ask and find informational questions and related educational answers by Medical Experts. Sahl Health is not a place for the practice of medicine, but Medical Experts through our partners can be a resource for reliable, relevant general health information. We hope these services will be of value to you. Please use them responsibly.</p>
                    <h4 class="h_style pt-3">We Do Provide Access to Doctors for International Care (Sahl Health International)</h4>
                    <p>On Sahl Health International support you can obtain 2nd opinion and access to international health care (if you are seeking health care from international health) This TOU applies to Sahl Health International.</p>
                    <h4 class="h_style pt-3">We Don't Create Doctor-Patient Relationships (Sahl Health)</h4>
                    <p>The use of Sahl Health does not create a doctor-patient relationship. Sahl Health contains Content, and may help you identify services or may offer services. Everything on Sahl Health, including Content accessed or Services provided through Sahl Health, is for your information, and should be used for informational purposes only. This means that Content and Services are not a substitute for medical advice, diagnosis, treatment, or care from your physician.
                    </p>
                    <h4 class="h_style pt-3">We Aren't Your Doctor (Sahl Health) </h4>
                    <p>Whenever we use the words "your physician" or "your doctor" or "healthcare provider" or similar words on Sahl Health, including in these Terms of Use, we mean your personal doctor with whom you have of an actual, mutually acknowledged, doctor-patient relationship (or the same kind of formal, real-world relationship between you and your personal professional healthcare provider) within your country. Medical Experts on Sahl Health are not "your" primary care doctor, physician, or healthcare provider and you agree not to use Sahl Health as a substitute for interactions with your Primary Care Physician.</p>
                    <h4 class="h_style pt-3">We're Not for Use in Emergencies</h4>
                    <p>Never use Sahl Health or Content or Services in a potential or actual medical emergency.</p>
                    <h3 class="h_style">Remember Always...</h3>
                    <ul>
                        <li>SEEK THE ADVICE OF YOUR DOCTOR OR YOUR OTHER QUALIFIED HEALTHCARE PROVIDER WHENEVER YOU HAVE A PERSONAL QUESTION ABOUT A MEDICAL CONDITION OR SYMPTOM.</li>
                        <li>NEVER DISREGARD PROFESSIONAL MEDICAL ADVICE, OR DELAY SEEKING MEDICAL ADVICE OR TREATMENT, BECAUSE OF SOMETHING YOU READ OR LEARN ON SAHL HEALTH.</li>
                        <li>CALL 911 (OR YOUR LOCAL EMERGENCY SERVICE) OR YOUR DOCTOR IMMEDIATELY IF YOU BELIEVE YOU MAY OR DO HAVE A MEDICAL EMERGENCY.</li>
                    </ul>
                    <h4 class="h_style">Sahl Health Medical Experts</h4>
                    <h3 class="h_style pt-3">Independence of Sahl Health Medical Experts </h3>
                    <p>Sahl Health Medical Experts and professionals or specialists utilizing or featured on Sahl Health are not employees or independent contractor service providers of Sahl Health. Any opinions, advice, or information expressed by any such individuals are those of the individual and the individual alone and they do not reflect the opinions of Sahl Health. Sahl Health does not recommend or endorse any specific tests, physicians, products, procedures, opinions, or other information that may be mentioned on Sahl Health or by a licensee of Sahl Health.
                        <br>
                        The inclusion of professionals and specialists on Sahl Health or in any professional directory on Sahl Health does not imply recommendation or endorsement of such professional nor is such information intended as a tool for verifying the credentials, qualifications, or abilities of any professional contained therein. SUCH INFORMATION IS PROVIDED ON AN "AS-IS" BASIS AND HEALTHTAP DISCLAIMS ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR PARTICULAR PURPOSE. HEALTHTAP SHALL IN NO EVENT BE LIABLE TO YOU OR TO ANYONE FOR ANY DECISION MADE OR ACTION TAKEN BY ANY PARTY (INCLUDING, WITHOUT LIMITATION, ANY USER) IN RELIANCE ON INFORMATION ABOUT PROFESSIONALS AND SPECIALISTS ON SAHL HEALTH. The use of Sahl Health by any entity or individual to verify the credentials of professionals or specialists is prohibited.<br>
                        All opinions and statements expressed by Sahl Health Medical Experts on or through Sahl Health are solely the individual and independent opinions and statements of such individuals and do not reflect the opinions of Sahl Health, its affiliates or any other organizations or institutions to which such Sahl Health Medical Expert or such specialist or professional is affiliated or provides services.
                    </p>
                    <h3 class="h_style">Your Account and Your Use of Sahl Health</h3>
                    <h4 class="h_style pt-3">You are responsible for your account: keep your password and real name private.</h4>
                    Accurate and complete registration information is required to use Sahl Health. You are responsible for the security of your passwords and for any use of your account. Please immediately notify us of any unauthorized use of your password or account. Allowing any other person or entity to use your identity for posting on or using Sahl Health is not permitted. Do not include your real name or any other information that could be used to identify you in anything you post that is publicly visible on Sahl Health (such as in questions or other public submissions).
                    <h4 class="h_style pt-3">Your use must be legal and you must be an adult to use Sahl Health.</h4>
                    Sahl Health is a Business Associate of health care providers, professionals under security law known as HIPAA. Your personal information will be stored in a secure manner. Sahl Health has implemented various encryption and security technologies and procedures to protect, from unauthorized access, your personal information which is stored in our computer systems. We also maintain standard physical and electronic procedural safeguards that limit access to your personal information to our employees (or people working on our behalf and under confidentiality agreements) who, through the course of standard business activities, need to access your personal information. Full access to the system is enabled only by usernames and passwords. You are fully and solely responsible for any and all use of the system using your username and password. We reserve the right to revoke or deactivate your username and password at any time.
                    Your use of Sahl Health and any Content and Services must comply with all applicable country state laws, regulations, and ordinances. Currently, you must be at least 16 years old to use Sahl Health and at least 18 years old to register on Sahl Health portal Services.
                    <h4 class="h_style pt-3">We'll send you notices and information.</h4>
                    For more details about when and how we can communicate with you, please consult our Privacy Statement.
                    <h3 class="h_style">Content and Services</h3>
                    <h4 class="h_style pt-3">Sahl Health is a Free Service That Offers Paid Services. </h4>
                    It's free to read articles, ask health questions and receive health answers and tips. Sahl Health also provides optional Services and Content that can be accessed for a fee. We will never ask you for your credit card or other payment information unless you indicate that you would like to use a paid service.
                    <h4 class="h_style pt-3">Sahl Health must be used responsibly.</h4>
                    You agree to use the website, portal and apps and any Service responsibly, and in a manner that is not: unlawful, threatening, harassing, abusive, defamatory, slanderous, libelous, harmful to minors, vulgar, gratuitously violent, obscene, pornographic, indecent, lewd, invasive of another's privacy, or racially, ethnically or otherwise offensive, hateful or abusive. You also agree not to intentionally overuse any Service or Premium Service, or use any Service or Premium Service for medically inappropriate purposes.
                    <h4 class="h_style pt-3">Sahl Health does not guarantee the accuracy of Third Party Content and service. </h4>
                    Sahl Health has no editorial control over or responsibility for Content provided by third parties and any opinions, statements, products, services or other information expressed or made available by third parties (including Medical Experts) or users on Sahl Health are those of such third parties or users. We make no representations about the accuracy or reliability of any opinion, statement or other information provided by any third party, and do not represent or warrant that your use of the Content displayed or referenced on Sahl Health will not infringe rights of third parties not owned by or affiliated with Sahl Health.
                    <br>We do not control, endorse, verify the truth or accuracy of, or review content outside of Sahl Health and we are not responsible for such content. The information, software, data, or other contents (including opinions, claims, comments) contained in linked references are those of the companies or individuals responsible for such External Content and Services and cannot be attributed to Sahl Health. We do not warrant, nor are we in any way responsible for, information, software, data, privacy policies, related or pertaining to External Content and Services.
                    <h4 class="h_style pt-3">You agree that we may send you limited personal information by email, SMS and mobile telephone notification. </h4>
                    When you use action-oriented features on Sahl Health Services including subscriptions you agree that Sahl Health may send you automatically via e-mail, mobile telephone or other contact information provided by you in your account settings, content including but not limited to, reminders relating to health or recommended actions for you. You understand and agree that by using these features, you are opting into receiving your own protected health information by email, SMS or mobile telephone notification, which is not secure. You also understand and agree that by receiving such protected health information by e-mail, SMS or mobile telephone notification, you will be charged by your wireless or internet provider and that such e-mails, SMS or mobile telephone notification may be generated by an automated dialing system. You control the utility, and the privacy, of the reminders you receive. In your account settings, you can control what information is sent to you, and where it's sent, and you can unsubscribe or opt-out from receiving reminders via email, SMS or mobile telephone notification, or any of them. If you prefer not to receive personal information by email or mobile notification, you agree to update your account notification settings.
                    <h4 class="h_style pt-3">Use of Your Information</h4>
                    We only use data you share with Sahl Health as set forth in the Sahl Health Privacy Statement, your account Settings, and in accordance with applicable law.
                    <h4 class="h_style pt-3">We cannot control external communications (including email, SMS, and notifications).</h4> Email, and short message service (SMS), text message communications and mobile push notifications from the Apps are not encrypted. You can opt out of receiving email, SMS/text messages, and mobile push notifications. Although unlikely, it is possible for these communications to be intercepted or accessed without your authorization, and by using the Apps, you release Sahl Health from any liability arising from or related to any such interception or unauthorized access.
                    <h3 class="h_style">Property Rights</h3>
                    <h4 class="h_style pt-3">Sahl Health owns or has rights to the Content and Services</h4>
                    When you use the website, portal or apps, you do so under a license from us. Your license to use Sahl Health is personal, revocable, non-assignable, and nonexclusive. This means that you may not use the system portal, website or apps for any commercial purpose, that we can take away your right to use them, that you cannot give this license away to someone else, and that other members can use our Content and Services. All right, h_style and interest in and to the Apps and the Content, together with all intellectual property rights embodied therein (including without all engagement, rating, and ranking systems and methodologies on the Apps) are the property of Sahl Health or our affiliates, excluding your rights under law to any information or Content. Rights retained by other parties in the Content are their respective rights.
                    <h4 class="h_style pt-3">You must ask our permission to use our Trademarks.</h4>
                    We have obtained or applied for various Trademarks and service marks. Sahl Health, the Sahl Health logo, other Sahl Health Trademarks and service marks and other Sahl Health logos and product and service names are our trademarks (the "Sahl Health Marks"). If you would like to use or display any Sahl Health Marks, you must ask our permission. Without our prior written permission, or according to the media use guidelines we publish, you agree not to display or use in any manner the Sahl Health Marks. All trademarks, brands, and content on Sahl Health are the property of their respective owners.
                    <h4 class="h_style pt-3">You agree not to infringe our Copyrights, Trademarks, Trade Secrets, Patents or other intellectual property rights.</h4>
                    <h4 class="h_style pt-3">You agree not to engage in any activity that would constitute copyright infringement with respect to the Content. </h4>
                    You may not reproduce, create derivative works of, distribute, publicly perform or publicly display the Content or any portion thereof without our prior written consent. You may, however, use the portal, website, apps as they are designed and intended to be used, including using features which allow you to re-post Content or portions of Content, including those which permit you to distribute Content through other third party applications and mediums (such as Facebook or Twitter), so long as you do not modify that Content or the functionality of those features in any way.
                    <h4 class="titlt pt-3">You agree not to access, attempt to access, or use our Data without our Permission. </h4>
                    You agree not to access, attempt to access, request access not authorized by the portal or apps or use any feature Content or data without our Permission. This means that you agree not to transmit, download, upload, post, sell, rent, license, transfer, disclose, mirror, frame, reverse engineer, decompile, disassemble, or use any aspect of the Apps or any Content, in whole or in part, in any form or by any means.
                    <h4 class="h_style pt-3">Contact us if you believe materials on our Apps infringe your copyright.</h4>
                    If you believe any materials accessible on or from Sahl Health infringe your valid and enforceable copyright, you may request removal of (or access to) those materials (or access thereto) from us by contacting us and providing us with information on support@sahlhealth.com
                    <h3 class="h_style">Submissions</h3>
                    <h4 class="h_style pt-3">You agree to abide by our Submission Guidelines </h4>
                    You agree that you will not upload or transmit any communications or content of any type that infringes or violates any rights of any party. The personal information you submit to Sahl Health is governed by the Privacy Statement, the terms of which shall govern in the event of any inconsistency with this Agreement. You agree that member or expert submissions will apply with Sahl Health Submissions Terms and Policies. If you are a member you agree to the User Submission Terms and Policies within this document. If you are an expert you agree to the Expert Submission Terms and Policies within this document.
                    <h4 class="h_style pt-3">You give us rights in what you submit. </h4>
                    With the exception of any personal data or information you submit (which shall be maintained in accordance with our Privacy Statement) and the rules and regulations promulgated thereunder (as amended to date, "HIPAA"), if you make any submissions (by email or otherwise) on, to or through Sahl Health, including but not limited to data, questions, comments, suggestions, business information, ideas, concepts or inventions, you make such submission without any restrictions or expectation of compensation or of confidentiality, and you agree that your submissions may be used without restriction for any purpose whatsoever, and you automatically grant-or warrant that the owner of such content or intellectual property has expressly granted-Sahl Health the complete right to freely use such submissions in any way, commercial or otherwise, and for any purpose whatsoever, including the right to use, reproduce, modify, adapt, publish, transmit, translate, create derivative works from, publicly perform or display (in any media or form now known or hereafter developed), or otherwise communicate to the public, in the form of a royalty-free, perpetual, irrevocable, worldwide nonexclusive license. Sahl Health may sublicense its rights. Such submissions will be treated as non-confidential and nonproprietary and will become the property of Sahl Health, and Sahl Health shall be free to use any ideas, concepts, know-how, or techniques contained in any communication you send for any purpose whatsoever, including, without limitation, developing and marketing products using such information. Sahl Health does not accept unsolicited recruiter or similar submissions and does not pay fees for any such parties without a current contract on file, and you agree that any submissions of candidates by a recruiter or other third party without a valid and signed recruiting agreement in place with Sahl Health prior to such submission will not be subject to any recruiter or similar fees.
                    <h4 class="h_style pt-3">About Sahl Health Medical Experts</h4>
                    Medical Experts on the portal, website or apps include respected health product and service providers, health professionals at national and international level. Partners or medical professionals whose licenses are or become suspended or revoked, for any reason, are not permitted and agree not to participate in any way, including but not limited to submitting Content to Sahl Health.
                    <h4 class="h_style pt-3">Our users have a right to the privacy of their identity. </h4>
                    Sahl Health does not disclose personally identifiable information about our members (please see our Privacy Statement for details), however you understand and agree that if you choose to use Sahl Health Portal Membership Services, that personally identifiable information will be visible to the partners with whom you interact.
                    <h3 class="h_style">Termination</h3>
                    <h3 class="h_style pt-3">All of our users are required to honor this Agreement. </h3>
                    Your permission to use the Content and Services ends immediately if you violate any of the terms of this Agreement. We may place limits on, modify, or terminate your right to access and use Sahl Health Services and/or Content at any time. This suspension or termination may delete information, files, and other previously available Content.
                    <h3 class="h_style">Changes to this Agreement</h3>
                    <h4 class="h_style pt-3"> We may update these Terms of Use.</h4>
                    When we make changes, we will revise the "last modified" date at the top of this document. We encourage you to review these Terms of Use periodically. Your continued use of Sahl Health constitutes your agreement to the changed Terms of Use.
                    <h3 class="h_style">Indemnification & Exclusions and Limitations</h3>
                    <h4 class="h_style pt-3">Exclusion of Warranties</h4>
                    THE WEBSITE, PORTALS AND APPS AND THE CONTENT AND SERVICES ARE PROVIDED "AS IS." NEITHER SAHLHEALTH PARTNERS, HEALTH PROFESSIONALS, NOR ANY OF OUR LICENSORS MAKE ANY EXPRESS WARRANTIES AND WE AND EACH OF THEM DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING IMPLIED WARRANTIES OF ACCURACY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. NEITHER WE NOR ANY OF OUR LICENSORS MAKE ANY WARRANTY THAT CONTENT OR SERVICES SATISFY GOVERNMENT REGULATIONS INCLUDING THOSE REQUIRING DISCLOSURE OF INFORMATION ON PRESCRIPTION PRODUCTS. HEALTHTAP AND THE CONTENT AND SERVICES WERE DEVELOPED FOR USE IN THE AFRICA, AND NEITHER WE NOR ANY OF OUR LICENSORS MAKE ANY REPRESENTATION CONCERNING SAHL HEALTH AND THE CONTENT OR SERVICES WHEN USED IN ANY OTHER REGIONS.
                    <h4 class="h_style pt-3">Limitation of Liability of Sahl Health;</h4>
                    We cannot and do not assume any responsibility or liability for the use or misuse, by you or any third party, of any Content or other information submitted, transmitted, or received via our website, portal or apps.
                    <h4 class="h_style pt-3">Use at your own risk</h4>
                    The website, portal, apps and the Content are provided on as "as is" basis. NEITHER WE, NEITHER SAHLHEALTH PARTNERS, HEALTH PROFESSIONALS, NOR ANY OF OUR LICENSORS MAY BE HELD LIABLE UNDER THIS AGREEMENT FOR ANY DAMAGES OTHER THAN DIRECT DAMAGES, EVEN IF THE PARTY KNOWS OR SHOULD KNOW THAT OTHER DAMAGES ARE POSSIBLE, OR THAT DIRECT DAMAGES ARE NOT A SATISFACTORY REMEDY. THE LIMITATIONS IN THIS SECTION APPLY TO YOU ONLY TO THE EXTENT THEY ARE LAWFUL IN YOUR JURISDICTION. WE DISCLAIM ALL WARRANTIES EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTIES' RIGHTS, AND FITNESS FOR PARTICULAR PURPOSE. Specifically, and without limiting the foregoing, We, our licensors, and our suppliers, make no representations or warranties about: (i) the accuracy, reliability, completeness, current-ness, or timeliness of the Content provided on or through the use of Sahl Health, whether by Sahl Health or any other party; or (ii) the satisfaction of any government regulations requiring disclosure of information on prescription products or the approval or compliance of any software tools with Sahl Health. Any location data accessed via the apps may be inaccurate or incomplete and any use of such data is at your own risk.
                    <br>Sahl Health, its licensors, its suppliers, or any third parties mentioned on Sahl Health are not liable for any personal injury, including death, attributable to or caused by your use or misuse of Sahl Health or Content (including member supplied Content or Medical Expert supplied Content). Any claims arising in connection with your use of Sahl Health or any Content must be brought within one (1) year of the first date of the event giving rise to such action. Remedies under these Terms and Conditions are exclusive and are limited to those expressly provided for in these Terms and Conditions. The limitations of liability in this section do not apply to breaches of intellectual property provisions by you or your indemnification obligations relating hereunder.
                    <h4 class="h_style pt-3">Remedies</h4>
                    IF YOU ARE DISSATISFIED WITH ANY OF THE CONTENT OR MATERIALS ON OUR SITE, OR ANY SERVICES OR INFORMATION AVAILABLE THROUGH THE SITE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING OUR SITE. THIS LIMITATION APPLIES EVEN IF YOUR REMEDIES UNDER THIS AGREEMENT FAIL OF THEIR ESSENTIAL PURPOSE.
                    <h3 class="h_style">Licensed Content</h3>
                    <h4 class="h_style pt-3">Certain Content may be licensed from third-parties. </h4>
                    The licenses for some of this Content may contain additional terms. When such Content licenses contain additional terms, we will make these terms available to you on those pages, in the Terms of Use or in the Additional Information section of our Apps (which is incorporated herein by reference).
                    <h3 class="h_style">General Legal Terms</h3>
                    <h4 class="h_style pt-3">Trademarks</h4>
                    Sahl Health is a registered Trademark of Sahl Health Inc. Any other trademark, brand, or content on Sahl Health that is not the property of Sahl Health is the property of its respective owner.
                    <h4 class="h_style pt-3">General Terms</h4>
                    This Agreement, and the other agreements referenced in it (like our Privacy Statement and Cookie Policy), is the entire agreement between you and us relating to Sahl Health. This Agreement replaces any prior agreements unless such prior or subsequent agreement explicitly provides otherwise and specifically references this agreement. If there is any conflict between this agreement and a mutually signed written agreement between you and us related to Sahl Health, the signed written agreement will control.
                    <br>We reserve the right to modify or discontinue our Content and Services (including but not limited to Sahl Health Services with or without notice to you, and you agree that we are not liable to you or any third party should we modify or discontinue any services, and that your only recourse is to cease using the Services. Continued use of Services following any such changes will indicate your acknowledgement of such changes and satisfaction with the Services as modified.
                    <br>Other parties may have rights under this agreement. A "third party beneficiary" is another party (for example, a company) who is not directly mentioned in an agreement, but who may have some rights arising out of an agreement. Our licensors may be third party beneficiaries to this Agreement pursuant to our agreements with them. To the extent our licensors are third party beneficiaries to this Agreement, the rights and protections provided to us under this Agreement inure to their benefit.
                    <br>If we provide you with a translation of the English language version of this agreement, the English language version of this agreement will control if there is any conflict.
                    <br>If we choose not to enforce any provision of this Agreement, we retain the right to enforce it in the future. This means that the failure to enforce any provision of this Agreement does not constitute a waiver of that provision. If any provision in this Agreement is found to be unenforceable, it and any related provisions will be interpreted to best accomplish the unenforceable provision's essential purpose.
                    <br>Nothing in this agreement limits either party's ability to seek equitable relief.
                    <h4 class="h_style pt-3">Arbitration Agreement</h4>
                    Sahl Health Terms of use require the use of arbitration to resolve disputes and also limits the remedies available to you in the event of a dispute. Most concerns can be resolved quickly by contacting our support department at support@sahlhealth.com . In the unlikely event that our support team is unable to resolve a legitimate legal complaint you may have (or if Sahl Health has not been able to resolve a dispute it has with you after attempting to do so informally), we each agree to resolve those disputes through binding arbitration or small claims instead of in courts of general jurisdiction. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, allows for more limited discovery than in court, and is subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Any arbitration under this Agreement will take place on an individual basis; class arbitrations and class actions are not permitted. We request that you work with us to resolve any disputes for 90 days after notifying us of such issues before filing arbitration.
                    <h4 class="h_style pt-3">Agreement</h4>
                    We want to address your concerns without a formal arbitration or case. Before filing a claim against Sahl Health, you agree to make a good faith effort to try to resolve the dispute informally by contacting support@sahlhealth.com  and responding promptly to any related communications. We'll try to resolve the dispute by contacting you via email. If a dispute is not resolved within 90 days of submission, you or Sahl Health may bring a formal proceeding.
                    <br>This Arbitration Agreement ("Arbitration Agreement") is a condition of the Terms of User of Sahl Health and the Apps. The effective date of this agreement is July 2019 (the "Effective Date"). Any arbitration proceedings shall be conducted by the specific country Arbitration Association under its rules and procedures applicable at that time, or any other Supplementary Procedures for Consumer-Related Disputes (to the extent applicable), as modified by our Arbitration Agreement.
                    <br>A party who intends to seek arbitration must first send to the other, by certified mail, a written Notice of Dispute ("Notice"). The Notice to Sahl Health should be addressed to: Managing Director, Sahl Health, at the current company address indicated on the on the Sahl Health website (www.sahlhealth.com) ("Notice Address"). The Notice must (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought and the specific applicable legal basis for the requested relief ("Demand").
                    <br>The arbitrator will decide the substance of all claims in accordance with the country laws, including recognized principles of equity, and will honor all claims of privilege recognized by law. The arbitrator shall not be bound by rulings in prior arbitrations involving different Sahl Health users, but is bound by rulings in prior arbitrations involving the same user to the extent required by applicable law. The arbitrator's award shall be final and binding and judgment on the award rendered by the arbitrator may be entered in any court possessing jurisdiction over the parties, except for a limited right of appeal under the Arbitration Act.
                    <br>YOU AND SAHL HEALTH AGREE, AS PART OF THE ARBITRATION AGREEMENT, THAT EACH OF US MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS PART OF ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING. WE REFER TO THIS AS THE "PROHIBITION OF CLASS AND REPRESENTATIVE ACTIONS". UNLESS BOTH YOU AND WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN YOUR OR OUR CLAIM WITH ANOTHER PERSON'S OR PARTY'S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE OR CLASS PROCEEDING. THE ARBITRATOR MAY ONLY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY'S INDIVIDUAL CLAIM(S). ANY RELIEF AWARDED CANNOT AFFECT OTHER SAHL HEALTH .
                    <br>Except with respect to the Prohibition of Class and Representative Actions, if a court decides that any part of this Arbitration Agreement is invalid or unenforceable, the other parts of this Arbitration Agreement shall continue to apply. If a court decides that the Prohibition of Class and Representative Actions is invalid or unenforceable, then the entire Arbitration Agreement shall be null and void. The remainder of the User Agreement and its Legal Disputes Section will continue to apply.
                    <h4 class="h_style pt-3">Opt-Out Procedure; </h4>
                    The Opt-Out deadline for optin out of this Arbitration Agreement has passed. CLAIMS ARE TIME-BARRED. You agree that regardless of any statute or law to the contrary or the applicable dispute resolution process, any claim or cause of action you may have arising out of or related to use of the Service or otherwise under these must be filed within one (1) year after such claim or cause of action arose or you hereby agree to be forever barred from bringing such claim.
                    <h3 class="h_style">Sahl Health Guidelines: Health Providers</h3>
                    <h4 class="h_style pt-3">The Basics</h4>
                    On Sahl Health only informational questions submitted for educational purposes are allowed. No personal health questions are permitted - questions may describe a general situation, illustration, illness or symptoms but please do not provide facts that give questions the impression of being unique to a single patient.
                    <br>No requests for prescription, diagnosis or treatment should be made on Sahl Health. Any second opinions received on Sahl Health are not diagnosis, prescription, or treatment, and are for informational purposes only. The content of any response is at the sole discretion of the Medical Expert answering the question.
                    <br>There is no guarantee that any submitted question will be answered; questions are answered at the sole discretion of participating Medical Experts. No follow up questions or personal information should be included in Thanks notes or other posts on or through Sahl Health.
                    <h4 class="h_style pt-3">Health Provider Submissions</h4>
                    Please note: The following guidelines apply to Sahl Health, where the practice of medicine is not permitted. Different guidelines apply to Health Provider Services, where you can engage in virtual or physical consultations with patients within the context of a health provider-patient relationship.
                    <br>By submitting Content to Sahl Health you agree to abide by these guidelines and terms. A few things you should know:
                    <ul>
                        <li>Only informational Answers for educational purposes are allowed</li>
                        <li>No personal, individualized health answers are permitted</li>
                        <li>You have no obligation to answer any submitted question</li>
                        <li>Make Expert Submissions only when you reasonably believe that they are likely to be useful and helpful to Sahl Health members</li>
                        <li>Agree with Expert Submissions only when you have fully reviewed and actually agree with the content, and do not agree with your own Submissions</li>
                        <li>If you are accredited by Sahl Health as a partner you should be capable of providing the said health service or product and for this purpose, subject to the terms and conditions of the Agreement to provide service and product within it scope, capabilities and resources to Sahl Health members</li>
                        <li>The provider is a registered and licensed with relevant government bodies</li>
                    </ul>
                    IN CONSIDERATION FOR PERMISSION TO USE THE PUBLIC AREAS YOU AGREE TO ABIDE BY ALL OTHER TERMS OF USE WHEN POSTING AND NOT TO DO ANY OF THE FOLLOWING, WHICH CAN RESULT IN YOUR IMMEDIATE SUSPENSION OR TERMINATION AS A MEDICAL EXPERT:
                    <h4 class="h_style pt-3">Avoid Revealing Private Information </h4>
                    Feel free to interact professionally with members and create long-lasting relationships with those in your community. However, help us keep the personal information of our members confidential. Please don't refer to members in or on Content in Public Areas by their real names, even if this information has been disclosed to you.
                    <h4 class="h_style">Avoid Offending Others</h4>
                    Responses should always be appropriate. Brief, casual, and friendly responses are the most useful. Help Sahl Health remain a trusted resource, by avoiding potentially offensive content whenever possible.
                    <h4 class="h_style pt-3">Avoid Communications that Suggest a Physician-Patient Relationship</h4>
                    Share your professional expertise though answers that is evidence-based and consistent with accepted standards in the medical community. Sahl Health is for general questions. Refrain from using language that suggests an answer is provided for a single member. Unless you are in a Private Conversation with a user on Sahl Health, refrain from answering questions that solicit your individual opinion as a single Medical Expert. Avoid answering questions or providing answers that suggest a duty of care and a physician-patient relationship.
                    <h4 class="h_style pt-3">Avoid Commercial Responses </h4>
                    You are allowed to link to external websites that are both appropriate and related to your responses, but answers on Sahl Health should be complete and should not be used for primarily promotional purposes. Please do not plagiarize and cite sources where applicable. Using answers as a vehicle to promote a product or service is prohibited. Providing members with useful and beneficial information and attracting new member through useful Content is permitted, but mere schilling is not.
                    <h4 class="h_style pt-3">Avoid Advertising or Specifically Soliciting Patients </h4>
                    Visitors on Sahl Health can find your professional contact information through your Virtual Practice, and can contact you for an appointment. However, please avoid violating medical board rules regarding advertising and patient solicitation.
                    <h4 class="h_style pt-3">Avoid Disclosing Confidential Material </h4>
                    Be careful not to discuss privileged or confidential details of past or current patients, or accidentally revealing confidential information in an indirect way - such as by discussing hypothetical illustrations that could be traced back to specific patients.
                    <h4 class="h_style pt-3">Avoid Violating Board Rules </h4>
                    Avoid other actions that violate respective country board or other rules that apply to you.
                    <h4 class="h_style pt-3">Rules Governing Other Submissions</h4>
                    All other information, including suggestions, feedback, ideas, concepts and any other materials you disclose or offer to us on or in connection with Sahl Health or any Content, are governed by the general member submission terms of this Agreement. This means that these submissions are made without any restrictions and without any expectation of confidentiality or compensation. You agree not to assert any property right or moral right of any kind with respect to any such submissions. You agree to our standard terms governing media submissions, except for the prohibition against uploading a facial portrait image of yourself for your Profile picture. You agree that your likeness, photograph, name, biographical information and any and all other information appearing.
                    <h3 class="h_style">Your Rights</h3>
                    <h4 class="h_style pt-3">Medical Experts: Information;</h4> As a Sahl Health Partner, Medical Expert, you are required to register with and use your real name, professional contact information, and (if you choose to upload a picture) a real image of you in your Public Profile. You consent to Sahl Health use on or in connection with the website, apps, portal of your name, likeness, photograph, biographical information and other personal information provided by you to Sahl Health or publicly available about you.
                    <h4 class="h_style pt-3">Medical Experts: You Can Control Your Expert Submissions;</h4>  You retain the right to edit and delete your own Expert Submissions that appear in your Public Profile at any time. You also retain the right to use and create derivative works from your own Expert Submissions elsewhere (such as on your own practice website, blog, or in your own social media posts).
                    <h4 class="h_style pt-3">Medical Experts: Permission to Post and Use Expert Submissions;</h4>  When a Sahl Health Medical Expert submissions related to any Sahl Health feature or function and made for publication on Sahl Health (such as an answer to a question) (an "Expert Submission"), you grant Sahl Health an unrestricted right without limitation to use, reproduce, extract data from or add data to, publish and post any such Expert Submissions, including in connection with or on Sahl Health, including in connection with your name. You also give us the right to give or transfer all rights granted herein to others. While Expert Submissions generally are posted to Sahl Health, we do not have an obligation to post any particular Expert Submission on Sahl Health and reserve the right, at our sole discretion and for any reason whatsoever (including but not limited to an Expert Submission being reported to us), to not post and/or to remove any Expert Submissions at any time.
                    <h4 class="h_style pt-3">No Posting of Content Written by Interested Parties; </h4> Medical Experts may not publish Content under their own name that is written in whole or material part by (a) parties with a financial interest in any product or service mentioned in the Content, or (b) employees of Industry. Accepting compensation for posting Content to Public Areas and/or posting ghostwriting by Interested Parties on Sahl Health is prohibited.
                    <h3 class="h_style">Rules for submitting questions or posting Content on Sahl Health</h3>
                    <h4 class="h_style pt-3">You agree to our Terms and Conditions and Rules </h4>By using (including by accessing or attempting to access) Sahl Health you agree that we have the right (but are not obligated) to: investigate an allegation that a communication or Content does not conform to these Terms and Conditions and determine in our sole discretion to remove or request the removal of the communication or Content; remove Content (including member-submitted questions) that we determine, in our sole discretion, to be abusive, illegal, or disruptive, or that otherwise fails to conform to these Terms and Conditions; terminate a Expert access to Sahl Health upon any breach of any of these Terms and Conditions; terminate a Expert access to Sahl Health if the expert registration information and/or email address is no longer valid; and remove any communication in Sahl Health; regardless of whether such communication violates these standards. We reserve the right to take any other action we deem necessary to protect the personal safety of our guests, visitors, and the public.
                    <h4 class="h_style pt-3">Only submit what you have a right to submit </h4>If you make any such submission you agree that you will not send or transmit to Sahl Health any communication or content that infringes or violates any rights of any party. If you submit any business information, idea, concept or invention to Sahl Health by email or otherwise, you agree such submission is non-confidential for all purposes. You agree to only post or upload Media (like photos) that you have taken yourself or that you have all rights to post or transmit and license, and which do not violate copyright, trademark, privacy or any other rights of any other person. By uploading any media on Sahl Health, you are representing and warranting to us that you have permission from all persons appearing in your media for you to use the media in this way, and to grant the rights described in these Terms of Use. Never post a picture with someone else unless you have their explicit permission.
                    <h4 class="h_style pt-3">Be a responsible and sensitive community member </h4>It is strictly prohibited to upload media of any kind that contain expressions of hate, abuse, offensive images or conduct, obscenity, pornography, sexually explicit, medically inappropriate, or any material that could give rise to any civil or criminal liability under applicable law or regulations or that otherwise may be in conflict with these TOU our Privacy Statement or any other Sahl Health.
                    <h4 class="h_style pt-3">Don't upload any viruses or software; </h4>You agree that you will not upload any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or this Web site.
                    <h4 class="h_style pt-3">You grant us a right when you upload or submit media or content. </h4> We need to have the right to display the content and media you upload to us. By uploading any media, like a photo, (a) you grant to us a perpetual, non-exclusive, worldwide, royalty-free license to use, copy, print, display, reproduce, modify, publish, post, transmit and distribute the media and any material included in the media; and (b) you certify that any person pictured in the submitted media (or, if a minor, his/her parent/legal guardian) authorizes Sahl Health to use, copy, print, display, reproduce, modify, publish, post, transmit and distribute the media and any material included in such media; and (c) you agree to indemnify Sahl Health and its affiliates, directors, officers and employees and hold them harmless from any and all claims and expenses, including attorneys' fees, arising from the media and/or your failure to comply with these terms.
                    <h4 class="h_style pt-3">You understand that we may review and reject any submission. </h4>We reserve the right to review all media or any other submission prior to or after submission to the site and to remove any media or any submission for any reason, at any time, without prior notice, at our sole discretion.
                    <h3 class="h_style">Foreign Languages</h3>
                    Where Sahl Health content or services (including these Terms of Use) are translated into languages other than English, all such translations are for the convenience of our users only, and Sahl Health is not responsible or liable in the event of any inaccuracy in such translation. In the event of a conflict between the English-language version of these Terms of Service, or any other content on Sahl Health, and a version that has been translated into another language, the English-language version shall control and apply.
                    <strong class="text-center">Date last modified: July 2019</strong>
                </div>
            </div>
        </div>
    </div>



@endsection
